name: Docker CI/CD with Trivy Scanning

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code- name: Checkout code
      - uses: actions/checkout@v3

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t yourusername/my-app:${{ github.sha }} .

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Run Trivy vulnerability scan
      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: yourusername/my-app:${{ github.sha }}
          format: table
          exit-code: 1  # Fail the build if vulnerabilities are found
          severity: CRITICAL,HIGH  # Only fail on critical or high severity vulnerabilities
          output: trivy-results.txt

      # Push the image to Docker Hub if no vulnerabilities are found
      - name: Push to Docker Hub
        if: success()  # Only run if previous steps succeed
        run: |
          docker push yourusername/my-app:${{ github.sha }}
          echo "Image successfully pushed to Docker Hub: yourusername/my-app:${{ github.sha }}"

      # Log results to terminal (this will appear in GitHub Actions logs)
      - name: Log Scan Results
        if: always()  # Run even if the workflow fails
        run: |
          if [ -f trivy-results.txt ]; then
            cat trivy-results.txt
          else
            echo "No vulnerabilities found."
          fi